Notes.Web.PL/Controllers/NoteController.cs
using Microsoft.AspNetCore.Mvc;
using Notes.Web.PL.Models;
using System.Diagnostics;
using Notes.BLL.BLL;
using Notes.DAL.DAL;
using Notes.DALInterfaces;
using Notes.BLLIntefaces;
using Notes.Common.Entities;
using Microsoft.AspNetCore.Authorization;


namespace Notes.Web.PL.Controllers
{
    public class NoteController : Controller
    {
        private readonly ILogger<NoteController> _logger;
        private INotesLogic _notesLogic;

        public NoteController(ILogger<NoteController> logger, INotesLogic notesLogic)
        {
            _logger = logger;
            _notesLogic = notesLogic;
        }
        public async Task<IActionResult> AddNote(UserNoteModel note)
        {

            if (ModelState.IsValid)
            {
                string login = User.Identity.Name;
                var user = await _notesLogic.GetAccount(login);
                var name = note.Name;
                var text = note.Text;
                var creationDate = DateTime.Now;


                await _notesLogic.AddNote(user.Id, name, text, creationDate);
                return RedirectToAction("GetUsersNote", "Home");
            }

            return View(note);
        }

        public async Task<IActionResult> RemoveNote(int id)
        {
            await _notesLogic.RemoveNote(id);
            return RedirectToAction("GetUsersNote", "Home");
        }

        public async Task<IActionResult> EditNote(int id, UserNoteModel noteModel)
        {
            if (ModelState.IsValid)
            {
                var name =noteModel.Name;
                var text =noteModel.Text;
                var creationDate = DateTime.Now;
                //!!!!!!!ПОМЕНЯТЬ КОРОЧЕ НА 4 АРГУМЕНТА МЕТОД EditNote ВЕЗДЕ
                //!!!!!!!!!!!!!!!!!!
                //!!!!!!!!!!1
                await _notesLogic.EditNote(id, text);
                return RedirectToAction("GetUsersNote", "Home");
                //return RedirectToAction("GetNote", "Note");
            }
            return View(noteModel);
        }

        public async Task<IActionResult> GetNote(int id)
        {
            var note = await _notesLogic.GetNote(id);
            //var note = await _notesLogic.GetNote(4);
            var noteModel = UserNoteModel.NoteFromEntity(note);
            return View(noteModel);
        }
    }
}

Notes.Web.PL/Views/Note/AddNote.cshtml
@model Notes.Web.PL.Models.UserNoteModel

@{
    ViewData["Title"] = "AddNote";
}

<h1>AddNote</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddNote">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetUsersNote" asp-controller="Home"> К моим заметкам</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Notes.Web.PL/Views/Note/EditNote.cshtml
@model Notes.Web.PL.Models.UserNoteModel

@{
    ViewData["Title"] = "EditNote";
}

<h1>EditNote</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditNote">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
           

            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetUsersNote" asp-controller="Home" > К моим заметкам</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Notes.Web.PL/Views/Note/GetNote.cshtml
@model Notes.Web.PL.Models.UserNoteModel

@{
    ViewData["Title"] = "GetNote";
}

<h1>GetNote</h1>

<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "EditNote", "Note",  new { id=Model.ID }, null) |
    @Html.ActionLink("Delete", "RemoveNote", "Note", new { id=Model.ID }, null)|
    <a asp-action="GetUsersNote" asp-controller="Home"> К моим заметкам</a>
</div>

Notes.Web.PL/Views/Note/RemoveNote.cshtml
@model Notes.Web.PL.Models.UserNoteModel

@{
    ViewData["Title"] = "RemoveNote";
}

<h1>RemoveNote</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserNoteModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
    </dl>
    
    <form asp-action="RemoveNote">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>